MODEL:
  META_ARCHITECTURE: "DecoupledRetinaNet"
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/retinanet_R_101_FPN_3x/190397697/model_final_971ab9.pkl"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res3", "res4", "res5" ]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval [ "[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]" ]
  RETINANET:
    NUM_CLASSES: 1
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1333
  MAX_SIZE_TEST: 1333
DATASETS:
  TRAIN: ('dataset_train_synthetic',)
  TEST: ('dataset_test_real',)
SOLVER:
  STEPS: (3999, )
  MAX_ITER: 4000  # 16 epochs
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
TEST:
  EVAL_PERIOD: 500
VIS_PERIOD: 500
VERSION: 2
